// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akfmkqkecqqgeidwdxvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrZm1rcWtlY3FxZ2VpZHdkeHZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODc0OTUsImV4cCI6MjA2NzU2MzQ5NX0.Q5u6vRbf86kMSEQuoPbVgDFAS2xvOLXkiHHGCtbM8GY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});